### ISSUE TITLE
The parser does not return correct line number in Windows

### ISSUE THREAD

**Issue by k3ndo** [MrDave1999/dotenv.core#11]
The parser specifies the line number where the error occurred but it does not match the line number of the .env file. This problem only happens on Windows.

For example, I have the following .env file:
```
KEY1 = 1
KEY2 = 2
asdasd
KEY3 = 3
KEY4 = 4
```
On testing this, the parser throws the following exception:
> The parser found a line that has no key-value pair format. (Actual Value: asdasd, Line: 5)

So, it doesn't make sense, the error occurred on line 3 and not line 5. The funny thing is that this behavior only occurs on Windows but not on Linux. I tested this on a Linux distro like Linux Mint and the line number is correct.

It seems that the problem is this line:
https://github.com/MrDave1999/dotenv.core/blob/d9c5d470cc35e0d75717b0e33e66645bb7e7aee5/src/Parser/EnvParser.cs#L138

According to the documentation, the value that represents the `NewLine` property in Windows is `\r\n`. `Split` method is receiving that value and returning empty substrings.

Why does it return empty substrings? I don't know yet.

If we have such a string: 
```
KEY1 = 1\r\nKEY2 = 2\r\nasdasd\r\nKEY3 = 3\r\nKEY4 = 4
```
`Split` method splits the string in this way:
```
KEY1 = 1
""
KEY2 = 2
""
asdasd
""
KEY3 = 3
""
KEY4 = 4
```
In Linux this problem does not happen, because the `NewLine` property returns `\n`, so the `split` method will not return empty substrings.

I will make a PR to solve this issue.

**Comment by MrDave1999** [comment]
I found an easier solution without the need to use the `StringReader` class:
```cs
var newLines = new[] { "\r\n", "\n", "\r" };
var lines = dataSource.Split(newLines, StringSplitOptions.None);
```
