### ISSUE TITLE
.env.*.local is moved to publish 

### ISSUE THREAD

**Issue by kkharji** [MrDave1999/dotenv.core#145]
Hello again @MrDave1999,

So I've experimenting and integrating `DotEnv` this week. One thing I was supersized to find is when I publish with `DotEnv.Core.Props` it includes `.env.*.local` which I suppose isn't the intended purpose ? no?

Thanks

**Comment by MrDave1999** [comment]
Hello @kkharji,

What happens is that `DotEnv.Core.Props` follows these conventions:

- `.env.{name}` (e.g., .env.production.local).
- `{name}.env` (e.g., production.local.env).

In this case the package copies any file starting with `.env`, e.g., `.env.dev.local`.

If you really don't want the `.env.*.local` files to be copied, you can try to redefine the `DefaultItemExcludes` property from your `.csproj` file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotEnv.Core.Props" Version="1.0.1" />
  </ItemGroup>
  
  <!-- Redefine the DefaultItemExcludes property -->
  <PropertyGroup>
    <DefaultItemExcludes>
      $(DefaultItemExcludes);
      **\.env.*.local
    </DefaultItemExcludes>
  </PropertyGroup>

</Project>
```

**Comment by kkharji** [comment]
Awesome that works. Thank you for the detailed example @MrDave1999 🙏
