### ISSUE TITLE
Parent LoadEnv

### ISSUE THREAD

**Issue by kkharji** [MrDave1999/dotenv.core#147]
Hello @MrDave1999 ,

I have a problem where all my packages in repo share the same env variables.

Not sure if LoadEnv can read from parent directory. I have created linux symoblic links but it breaks on windows.

Any recommendations

Thanks

**Comment by MrDave1999** [comment]
Hello @kkharji,

Yes, the `EnvLoader.LoadEnv` method also searches in the parent directories.

See [API documentation](https://mrdave1999.github.io/dotenv.core/api/DotEnv.Core.IEnvLoader.LoadEnv.html#DotEnv_Core_IEnvLoader_LoadEnv) (remarks).

**Comment by kkharji** [comment]
Oh yes, it does indeed.

I managed to run test successfully. 

Awesome design 👏🏻 


My directory structure 

```
. project.sln
  - Core
  - Domain 
  - AppOne
  - AppRwo

```

**Comment by MrDave1999** [comment]
Could you use the `tree` command from terminal to get the directory tree of your project? To see it more clearly.

**Comment by kkharji** [comment]
I'm away from the computer but it's in first level root and each package are in second level

**Comment by kkharji** [comment]
Added the following to one of the packages and it works:

```
    <Content
      Include="..\**\.env*"
      Exclude="..\**\.env.*.local"
      CopyToPublishDirectory="PreserveNewest"
     />

```

Now LoadEnv and this changes made it maintainable for me to use env in top level.

Thanks @MrDave1999

**Comment by kkharji** [comment]
Ops .. I think it failed in reading while running tests package.

I get:

```
System.IO.FileNotFoundException : Could not find file '/home/kkharji/exper/Repositories.Tests/.env.development'
```

tree:

```
.
├── .config
├── .csharpierrc.yaml
├── .env.development
├── .env.development.local
├── .env.production
├── .git
├── .github
├── .gitignore
├── Client
├── Core
├── Domain
├── Repositories
├── Repositories.Tests
├── Api
└── project.sln
```

**Comment by kkharji** [comment]
Oh never mind it works now, forgot a symlink in tests directory. Sorry

**Comment by MrDave1999** [comment]
@kkharji Yes, in that case it does not help much to use the `DotEnv.Core.Props` package, since its .env files are outside the project directory.

So there is no choice but to create your own configuration but I recommend you to add this item in a `.props` file so you can reuse it in several projects:
```xml
<!-- file: MyProject.props -->
<Project>

  <ItemGroup>
    <Content
      Include="..\**\.env*"
      Exclude="..\**\.env.*.local"
      CopyToPublishDirectory="PreserveNewest"
     />
  </ItemGroup>

</Project>
```
Then you import it into the .csproj file of your application:
```xml
<Import Project="..\MyProject.props" />
```
This is only a sample, you may have to modify the paths.

**Comment by kkharji** [comment]
Oh wow that's a neat little trick. Thanks so much @MrDave1999 🙏
